version: '3.7'
services:
  dackbot:
    restart: unless-stopped
    build:
      context: .
      args:
        - DACKBOT_BOT_TOKEN=${DACKBOT_BOT_TOKEN}
        - DACKBOT_OWNER_ID=${DACKBOT_OWNER_ID}
